apiVersion: v1
kind: Namespace
metadata:
  name: gitops-with-tanzu
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: gitops-with-tanzu
  namespace: gitops-with-tanzu
spec:
  fetch:
    imgpkgBundle:
      image: ghcr.io/alexandreroman/gitops-with-tanzu-repo:stable
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-with-tanzu-sa
  namespace: gitops-with-tanzu
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-with-tanzu-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-with-tanzu-role-binding
subjects:
- kind: ServiceAccount
  name: gitops-with-tanzu-sa
  namespace: gitops-with-tanzu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-with-tanzu-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-default-sa
  namespace: gitops-with-tanzu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: core-default-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: core-default-role-binding
subjects:
- kind: ServiceAccount
  name: core-default-sa
  namespace: gitops-with-tanzu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: core-default-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-default-sa
  namespace: gitops-with-tanzu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-default-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-default-role-binding
subjects:
- kind: ServiceAccount
  name: monitoring-default-sa
  namespace: gitops-with-tanzu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-default-role
